### ISSUE TITLE
Issue folder

### ISSUE THREAD

**Issue by Lxgends** [kp2129/todomist#8]
Jigger

**Comment by Skrazzo** [comment]
![image](https://github.com/kp2129/todomist/assets/58330666/5f6baf87-ee2c-4a52-abf3-da6e8de9d3f6)
Tad kad roberts

**Comment by Skrazzo** [comment]
![image](https://github.com/kp2129/todomist/assets/58330666/8de8b404-47ad-458b-9df9-1c3fc0d50552)
Laura is doing mimimi ZZZ

**Comment by Skrazzo** [comment]
![image](https://github.com/kp2129/todomist/assets/58330666/e0cb7df6-5c72-4caf-abc4-f858f4aa5e9a)

**Comment by Skrazzo** [comment]
![image](https://github.com/kp2129/todomist/assets/58330666/9cfd2ef9-b9f2-40ce-8fbd-afb1095219f3)
